meta-overc: rollback the system once it upgraded failed
Signed-off-by: fli <fupan.li@windriver.com>

diff --git a/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0 b/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
--- a/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
+++ b/meta-cube/recipes-support/overc-system-agent/files/overc-system-agent-1.2/container-scripts/dom0
@@ -311,6 +311,7 @@ list_container() {
 
 runcmd_in_container() {
 	$DOM0_CTL exec-cmd -n $1 $2
+	return $?
 }
 
 format_size() {
@@ -340,6 +341,7 @@ format_size() {
 
 rpm_upgrade() {
 	local container=$1
+	tag="0"
 
 	runcmd_in_container $container "smart update"
 	if [ ! $? -eq 0 ]; then
@@ -365,21 +367,36 @@ rpm_upgrade() {
 		snapshot $container
 	else
 		echo "*******************************************************************"
-		echo "  Warning: There isn't enough space left to snapshot conainer"
+		echo "  Error: There isn't enough space left to snapshot conainer"
 		echo "*******************************************************************"
+		return 1
 	fi
 
+	
 	tempdir="/tmp/tmpd.$RANDOM"
 	runcmd_in_container $container "mkdir -p $tempdir"
-	runcmd_in_container $container "cp -r /var/lib/rpm $tempdir"
-	runcmd_in_container $container "mount -t tmpfs tmpfs /var/lib/rpm"
+	runcmd_in_container $container "cp -r /var/lib/rpm $tempdir" 
+	runcmd_in_container $container "mount -t tmpfs tmpfs /var/lib/rpm" 
 	runcmd_in_container $container "cp -r $tempdir/rpm /var/lib/"
+
+	echo  $container >>/etc/overc/upgrade.lock
+
 	runcmd_in_container $container "smart upgrade -y"
+	if [ $? -ne 0 ]; then
+		tag="1"
+	fi
+
 	runcmd_in_container $container "cp -r /var/lib/rpm $tempdir"
 	runcmd_in_container $container "umount /var/lib/rpm"
 	runcmd_in_container $container "cp -r $tempdir/rpm /var/lib/"
 	runcmd_in_container $container "rm -rf $tempdir"
 	runcmd_in_container $container "sed -i /^CUBEUPDATE:/d /etc/motd"
+
+	if [ X"$tag" = "X1" ]; then
+		$OVERC_CCTL rollback -n $container -F -r
+		return 1
+	fi
+	sed -i '$d' /etc/overc/upgrade.lock
 }
 
 delete_container() {
@@ -586,6 +603,7 @@ case "${command}" in
 		verify_arg_set container
 		echo "RPM upgrade container: $container"
 		rpm_upgrade $container
+		retval=$?
 		;;
 	delete_snapshots)
 		verify_arg_set container
